# Generated by Django 3.0 on 2021-01-07 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0013_auto_20210106_1442'),
    ]

    operations = [
        migrations.RenameField(
            model_name='devorgopp',
            old_name='name_dev',
            new_name='name_devv',
        ),
    ]
