# Generated by Django 3.0 on 2021-01-07 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0014_auto_20210107_1947'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persfundingopp',
            old_name='logo',
            new_name='logoo',
        ),
    ]
