# Generated by Django 3.0 on 2021-02-03 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0019_orgprofile_name_ceo_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgprofile',
            name='coalition_name_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='اسم الشبكة / التحالف باللغة الانجليزية'),
        ),
    ]
