# Generated by Django 3.0 on 2021-02-24 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0020_orgprofile_coalition_name_en'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='org_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_position', to='orgs.OrgProfile', verbose_name='اسم المنظمة'),
        ),
    ]
